name: CI/CD Pipeline 

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment where workflow will run"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod
          - staging

jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        run: echo "Code cloned from GitHub"

  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: Build Application
        run: echo "Building the application"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: echo "Running tests"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Application
        run: echo "Deploying to ${{ github.event.inputs.environment }}"
