# packages - issues ya vulnerabilities (scan)
# pip-audit

name: Dependency Scan

on:
  workflow_call:
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Pip Audit
        run: pip install pip-audit

      - name: Install Project Dependencies
        run: pip install -r requirements.txt

      - name: Audit Dependencies
        run: pip-audit -r requirements.txt























