name: Deploy to Server

on:
  workflow_call:
    secrets:
      SSH_KEY_BASE64:
        required: true
      HOST:
        required: true
      USERNAME:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Decode SSH Key
        run: |
          echo "${{ secrets.SSH_KEY_BASE64 }}" | base64 -d > key.pem
          chmod 600 key.pem

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key_path: key.pem
          port: 22
          script: |
            cd /home/ubuntu

            # Pull latest code
            git pull origin main

            # Run container
            docker compose down
            docker compose up -d --build