name: DevSecOps Pipeline end to end pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Code OK"

  dependency-scan:
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - run: echo "Dependency OK"

  docker-lint:
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - run: echo "Docker OK"

  build-push:
    runs-on: ubuntu-latest
    needs: [dependency-scan, docker-lint]
    steps:
      - run: echo "Build OK"

  image-scan:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - run: echo "Scan OK"

  deploy:
    runs-on: ubuntu-latest
    needs: image-scan
    steps:
      - run: echo "Deploy Triggered"