name: DevSecOps Pipeline

on:
  push:

jobs:

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Code quality check"

  secrets-scan:
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - uses: actions/checkout@v4
      - run: echo "Secrets scan"

  dependency-scan:
    runs-on: ubuntu-latest
    needs: secrets-scan
    steps:
      - uses: actions/checkout@v4
      - run: echo "Dependency scan"

  docker-scan:   # 👈 rename (sir ke jaisa)
    runs-on: ubuntu-latest
    needs: secrets-scan
    steps:
      - uses: actions/checkout@v4
      - run: echo "Dockerfile scan"

  # 👇 build group create karne ke liye
  build:
    runs-on: ubuntu-latest
    needs: [dependency-scan, docker-scan]
    steps:
      - run: echo "Build stage started"

  build-and-push:
    runs-on: ubuntu-latest
    needs: build   # 👈 nesting create karega
    steps:
      - uses: actions/checkout@v4
      - run: echo "Build and push Docker image"

  trivy:   # 👈 sir ke jaisa naming
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - run: echo "Trivy installed"

  image-scanner:
    runs-on: ubuntu-latest
    needs: trivy   # 👈 nested feel aayega
    steps:
      - run: echo "Scanning image"

  deploy:
    runs-on: ubuntu-latest
    needs: image-scanner
    steps:
      - run: echo "Deploying app"