name: DevSecOps Pipeline

on:
  push:

jobs:

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Code quality check"

  dependency-scan:
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - uses: actions/checkout@v4
      - run: echo "Dependency scan"

  docker-lint:
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - uses: actions/checkout@v4
      - run: echo "Docker lint"

  secrets-scan:
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - uses: actions/checkout@v4
      - run: echo "Secrets scan"

  build-push:
    runs-on: ubuntu-latest
    needs: [dependency-scan, docker-lint, secrets-scan]
    steps:
      - uses: actions/checkout@v4
      - run: echo "Build and push Docker image"

  image-scan:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - uses: actions/checkout@v4
      - run: echo "Trivy scan"

  deploy:
    runs-on: ubuntu-latest
    needs: image-scan
    steps:
      - run: echo "Deploying app"