# Scan tthe dockerfile for issues & CVEs
name: Docker Lint

on:
  workflow_call:

jobs:
  docker-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Run Hadolint (Dockerfile Lint)
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile