name: Deploy to Server

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Decode SSH key
        run: |
          echo "${{ secrets.SSH_KEY_BASE64 }}" | base64 -d > key.pem
          chmod 600 key.pem

      - name: Deploy on Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key_path: key.pem
          port: 22
          script: |
            cd /home/ubuntu

            # Pull latest code
            git pull origin main

            # Run Docker Compose
            docker compose up -d --build