name: Hello Aniket

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello to user
        run: echo "Hello to user"

      - name: Say hello to username
        run: echo "Hello $USER"

      - name: Check Docker & Python version
        run: |
          docker --version
          python3 --version