name: hello aniket

on:
  push:
    branches: [main]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: say hello to user
        run: echo "hello to user"

      - name: say hello to username
        run: echo "hello $USER"
