name: Image Scan

on:
  workflow_call:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: aniket484/github-actions-app:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH